#!/bin/bash

# user
default_user="osckorea"
default_home="/home/osckorea"

# storage
default_storage=""

#k8s
rancher_master01="rancher_master01"
rancher_worker01="rancher_worker01"
master_node01="m1"
worker_node01="w1"

